config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :profiles
  resources :suppliers
  resources :clients
  resources :categories
  devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: [:show, :edit, :update, :destroy]

  def index
    @suppliers = Supplier.all
  end

  def show
  end

  def new
    @supplier = Supplier.new
  end

  def edit
  end

  def create
    @supplier = Supplier.new(supplier_params)

    respond_to do |format|
      if @supplier.save
        format.html { redirect_to @supplier, notice: 'Supplier was successfully created.' }
        format.json { render :show, status: :created, location: @supplier }
      else
        format.html { render :new }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @supplier.update(supplier_params)
        format.html { redirect_to @supplier, notice: 'Supplier was successfully updated.' }
        format.json { render :show, status: :ok, location: @supplier }
      else
        format.html { render :edit }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @supplier.destroy
    respond_to do |format|
      format.html { redirect_to suppliers_url, notice: 'Supplier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    def supplier_params
      params.require(:supplier).permit(:nombre, :direccion, :telefono)
    end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/suppliers/_form.html.erb
<%= simple_form_for(@supplier) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs form-group">
    <%= f.input :nombre %>
    <%= f.input :direccion %>
    <%= f.input :telefono %>
  </div>

  <div class="form-actions">
  <%= f.button :submit, class:"btn btn-info btn-block"%>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<div class="container p-4">
  <div class="row">
    <div class="col-md-4 mx-auto">
      <div class="card shadow">
        <div class="card-body">
          <h5 align="center">Editar proveedores</h5>
          <%= render 'form', supplier: @supplier %>

          <%= link_to 'Show', @supplier %> |
          <%= link_to 'Back', suppliers_path, class:"mt-2" %>
      
        </div>
      </div>
    </div>
  </div>
</div>

app/views/suppliers/index.html.erb
<div class="container">
  <h1>Proveedores</h1>
  <div>
    <%= link_to new_supplier_path, {class: "btn btn-info shadow"} do %>
    <%= fa_icon "plus-circle" %>
       Nuevo proveedor
    <% end %>
  </div>
  <br>
  <div class="card shadow mb-4">
    <div class="card-body">
      <div class="table-responsive">
        <p id="notice"><%= notice %></p>
        <table id="tablaCategories" class="table table-bordered table-hover">
        <thead>
        <tr>
          <th>Nombre</th>
          <th>Direccion</th>
          <th>Telefono</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @suppliers.each do |supplier| %>
          <tr>
            <td><%= supplier.nombre %></td>
            <td><%= supplier.direccion %></td>
            <td><%= supplier.telefono %></td>
            <td align="center"><%= link_to 'Mostrar', supplier, class: "btn btn-success btn-xs" %></td>
            <td align="center"><%= link_to 'Editar', edit_supplier_path(supplier), class:"btn btn-info btn-xs"%></td>
            <td align="center"><%= link_to 'Borrar', supplier, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-xs"%></td>
          </tr>
        <% end %>
      </tbody>
       </table>
      </div>
    </div>
  </div>
</div>

app/views/suppliers/new.html.erb
<div class="container p-4">
  <div class="row">
    <div class="col-md-4 mx-auto">
      <div class="card shadow">
        <div class="card-body">
          <h5 align="center">Nuevo proveedor</h5>
          <%= render 'form', supplier: @supplier %>

          <%= link_to 'Back', suppliers_path %>
        
        </div>
      </div>
    </div>
  </div>
</div>

app/views/suppliers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @supplier.nombre %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @supplier.direccion %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @supplier.telefono %>
</p>

<%= link_to 'Edit', edit_supplier_path(@supplier) %> |
<%= link_to 'Back', suppliers_path %>